### ISSUE TITLE
i-vector extraction

### ISSUE THREAD

**Issue by roblewis1237** [MaurizioFD/CFeCBF#1]
Hi Maurizio, the library and paper are amazing. Thanks for sharing. I'm working on something similar and was wondering how you extract the i-vectors from the audio signal? 
thanks

**Comment by MaurizioFD** [comment]
Hi,

I am sorry for the delay in my reply, I didn't receive the notification!
For details on this specific topic I suggest you contact the first author directly, Yashar Deldjoo.

Best
